all: clean
	@gcc -o quicksort_input quicksort_input.c
	@gcc -o quicksort_noinput quicksort_noinput.c
	@./quicksort_input
	@./quicksort_noinput

clean:
	@rm -f quicksort_input
	@rm -f quicksort_noinput